apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: integration-test
spec:
    collectors:
        - configMap:
            namespace: "{{ .Namespace }}"
            name: game-demo
            includeAllData: true
