ignore:

  - package:
      type: python

  # False positive https://github.com/anchore/grype/issues/316
  - vulnerability: CVE-2021-20277
    package:
      name: libldb
      version: 1.5.4-2.el7
      type: rpm
