name: auto-merge

on:
  # This workflow trigger may lead to malicious PR authors being able to obtain repository write permissions or stealing repository secrets. 
  # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  autoapprove:
    runs-on: ubuntu-latest

    # only run for dependabot prs
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - id: dependabot
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: auto-approve conditions
        id: auto-approve-conditions
        # only auto-approve if this is a minor or patch version update
        if: |
          (
            steps.dependabot.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.dependabot.outputs.update-type == 'version-update:semver-minor'
          )
        run: echo "::notice ::auto-approve conditions satisfied"

      - name: auto-approve
        uses: hmarr/auto-approve-action@v2
        if: ${{ steps.auto-approve-conditions.conclusion == 'success' }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  automerge:
    runs-on: ubuntu-latest
    needs: [ autoapprove ]

    # only run for dependabot prs
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:

      # auto-merge will wait for status checks that are required in the branch protection rules
      - name: auto-merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "1"
          MERGE_RETRIES: "12"
          MERGE_RETRY_SLEEP: "10000"
