name: build-test

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: succeed
        run: |
          sleep 100
          echo "SUCCESS!"
          exit 0

  build-test-success:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "::notice ::build test success"
