# This rebuilds a single image
name: build-image
on:
  workflow_dispatch:
    inputs:
      image:
        description: path to a Makefile that builds the image
        required: true
        default: addons/registry/build-images/s3cmd

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
    - name: Build image ${{ github.event.inputs.image }}
      env:
        IMAGE: ${{ github.event.inputs.image }}
      run: |
        make -C $IMAGE build scan
