name: build-test

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: succeed
      run: |
        echo "SUCCESS!"
        exit 0

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: fastify/github-action-merge-dependabot@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        target: minor
