name: build-test

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: succeed
        run: |
          sleep 100
          echo "SUCCESS!"
          exit 0

      - name: auto-approve
        uses: hmarr/auto-approve-action@v2
        # only run for dependabot prs
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
