name: test-target

on:
  pull_request:
  pull_request_target:
    # This workflow trigger may lead to malicious PR authors being able to obtain repository write permissions or stealing repository secrets. 
    # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    types: [ opened, synchronize, reopened, labeled ]

jobs:
  build:
    runs-on: ubuntu-latest
    # if the event is pull_request:
    #   - this is not a fork
    #   - and not dependabot
    # if the event is pull_request_target:
    #   - this is dependabot
    #   - or this is a fork and has label '@actions/safe-to-test'
    if: >
      ( github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository &&
        github.event.pull_request.user.login != 'dependabot[bot]'
      )
      ||
      ( github.event_name == 'pull_request_target' && 
        ( github.event.pull_request.user.login == 'dependabot[bot]' ||
          ( github.event.pull_request.head.repo.full_name != github.repository &&
            contains(github.event.pull_request.labels.*.name, '@actions/safe-to-test'
          )
        )
      )
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -o test ./cmd/test/main.go
