on: [push]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    # timeout-minutes: 5
    steps:

      - uses: actions/checkout@v2

      - name: install k3s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

      - name: install troubleshoot
        run: |
          RELEASE="$(curl -fsSL https://api.github.com/repos/replicatedhq/troubleshoot/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
          curl -fsSLO https://github.com/replicatedhq/troubleshoot/releases/download/$RELEASE/support-bundle_linux_amd64.tar.gz
          tar -xzf support-bundle_linux_amd64.tar.gz
          chmod +x support-bundle

      - name: run tests
        run: |
          export SUPPORT_BUNDLE_BINARY=`pwd`/support-bundle
          go test -v integration/support-bundle/integration_test.go
