name: integration

on:
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    # timeout-minutes: 5
    steps:

      - uses: actions/checkout@v2

      - name: install k3s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

      - name: install kots
        run: |
          RELEASE="$(curl -fsSL https://api.github.com/repos/replicatedhq/kots/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
          curl -fsSLO https://github.com/replicatedhq/kots/releases/download/$RELEASE/kots_linux_amd64.tar.gz
          tar -xzf kots_linux_amd64.tar.gz
          chmod +x kots
          echo "$KOTS_APP_LICENSE" > license.yaml # from github actions secret
          ./kots install qakotsregression/stable \
            --namespace qakotsregression \
            --shared-password mysupersecretpassword \
            --license-file license.yaml \
            --config-values integration/assets/config-values.yaml \
            --skip-preflights

      - name: download troubleshoot binary
        run: |
          RELEASE="$(curl -fsSL https://api.github.com/repos/replicatedhq/troubleshoot/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
          curl -fsSLO https://github.com/replicatedhq/troubleshoot/releases/download/$RELEASE/support-bundle_linux_amd64.tar.gz
          tar -xzf support-bundle_linux_amd64.tar.gz
          chmod +x support-bundle

      - name: run tests
        run: |
          export SUPPORT_BUNDLE_BINARY=`pwd`/support-bundle
          go test -v integration/support-bundle/integration_test.go
