name: scan

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:

  scan:
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan postgres for vulnerabilities
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: postgres:10.17
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'scan-output.sarif'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: scan-output
          path: scan-output.sarif
          retention-days: 1
      - name: Upload scan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: scan-output.sarif
