name: scan

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:

  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan postgres for vulnerabilities
        id: scan
        uses: emosbaugh/scan-action@inputs-ignore-unfixed
        with:
          image: docker.io/library/postgres:10.18
          acs-report-enable: true
          severity-cutoff: medium
          # ignore-unfixed: true
          fail-build: false

      - name: Upload Anchore scan SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: 'Upload Artifact'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: scan-output
          path: ${{ steps.scan.outputs.sarif }}
          retention-days: 1
