name: release

on:
  push:
    branches:
      - main

jobs:

  scan:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan postgres for vulnerabilities
        id: scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: postgres:10.17
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'scan-output.sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Upload scan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: scan-output.sarif
