name: support-bundle

on: [ pull_request ]

jobs:
  support-bundle:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        k8s_version: [v1.23.3-k3s1]
    steps:
      - uses: replicatedhq/action-k3s@main
        id: k3s
        with:
          version: ${{ matrix.k8s_version }}
          ports: '30000:30000'

      - name: Fails
        id: suite-minimal-rbac
        run: |
          exit 1

      - name: Generate support bundle on failure
        if: failure() && steps.suite-minimal-rbac.outcome == 'failure'
        env:
          # aws replicated dev account e2e-kots-support-bundle user
          AWS_ACCESS_KEY_ID: ${{ secrets.E2E_SUPPORT_BUNDLE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_SUPPORT_BUNDLE_AWS_SECRET_ACCESS_KEY }}
        run: |
          RELEASE="$(
            curl -sfL https://api.github.com/repos/replicatedhq/troubleshoot/releases/latest | \
            grep '"tag_name":' | \
            sed -E 's/.*"(v[^"]+)".*/\1/'
          )"
          curl -fsLO "https://github.com/replicatedhq/troubleshoot/releases/download/${RELEASE}/support-bundle_linux_amd64.tar.gz"
          tar xzf support-bundle_linux_amd64.tar.gz
          ./support-bundle -n default https://kots.io
          BUNDLE="$(ls -1 | grep 'support-bundle-.*.tar.gz')"
          aws s3 cp "${BUNDLE}" "s3://kots-e2e-build-test-support-bundles/${BUNDLE}"
          run: echo "::notice ::support bundle uploaded to https://kots-e2e-build-test-support-bundles.s3.amazonaws.com/${BUNDLE}"
