name: build-test

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: go build -o test ./cmd/test/main.go
